---
- name: Pobierz i dodaj klucz GPG dla repozytorium PostgreSQL
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Dodaj repozytorium PostgreSQL
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    update_cache: true

- name: Zainstaluj PostgreSQL
  ansible.builtin.apt:
    name: postgresql
    state: present
    update_cache: true
  become: true

- name: Instalacja pakietów PostgreSQL
  ansible.builtin.apt:
    name:
      - "postgresql-server-dev-{{ postgresql_version }}"
      - "postgresql-{{ postgresql_version }}-icu-ext"
      - "postgresql-contrib-{{ postgresql_version }}"
    state: present
    update_cache: true
  become: true

- name: Restart PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
    enabled: true
  become: true
  tags: postgresql
