---
- name: Ustaw lokalizację klastra PostgreSQL
  ansible.builtin.command: "locale -a"
  register: locale_check
  changed_when: false

- name: Upewnienie czy lokalizacja jest dostępna
  set_fact:
    postgresql_locale: "{{ (locale_check.stdout_lines | select('match', '^pl_PL.UTF-8$')) | first | default('C.UTF-8') }}"

- name: Sprawdź, czy klucz GPG dla repozytorium PostgreSQL jest już dodany
  ansible.builtin.command: "gpg --list-keys ACCC4CF8"
  register: gpg_key_check
  ignore_errors: true
  changed_when: false

- name: Pobierz i dodaj klucz GPG dla repozytorium PostgreSQL
  ansible.builtin.get_url:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    dest: /etc/apt/trusted.gpg.d/postgresql.asc
    mode: '0644'
  when: gpg_key_check.rc != 0

# Sekcja: Dodanie repozytorium PostgreSQL
- name: Sprawdź, czy repozytorium PostgreSQL jest już dodane
  ansible.builtin.shell: |
    grep -h '^deb .*postgresql.*pgdg' /etc/apt/sources.list /etc/apt/sources.list.d/*
  register: repo_check
  ignore_errors: true
  changed_when: false

- name: Dodaj repozytorium PostgreSQL
  ansible.builtin.apt_repository:
    repo: >
      deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main
    state: present
    update_cache: true
  when: repo_check.rc != 0

# Sekcja: Instalacja PostgreSQL
- name: Sprawdź, czy PostgreSQL jest już zainstalowany
  ansible.builtin.shell: "dpkg -l | grep postgresql"
  register: postgresql_check
  ignore_errors: true
  changed_when: false

- name: Zainstaluj PostgreSQL
  ansible.builtin.apt:
    name: postgresql
    state: present
  become: true
  when: postgresql_check.rc != 0

- name: Sprawdź, czy pakiety PostgreSQL są już zainstalowane
  ansible.builtin.shell: |
    dpkg -l | grep 'postgresql-server-dev\|postgresql-icu-ext\|postgresql-contrib'
  register: postgresql_packages_check
  ignore_errors: true
  changed_when: false

- name: Instalacja pakietów PostgreSQL
  ansible.builtin.apt:
    name:
      - "postgresql-server-dev-{{ postgresql_version }}"
      - "postgresql-{{ postgresql_version }}-icu-ext"
      - "postgresql-contrib-{{ postgresql_version }}"
    state: present
  become: true
  when: postgresql_packages_check.rc != 0

# Sekcja: Konfiguracja lokalizacji bazy danych
- name: Upewnij się, że katalog /var/lib/postgresql istnieje
  ansible.builtin.file:
    path: /var/lib/postgresql
    state: directory
    owner: postgres
    group: postgres
    mode: '0755'
  become: true

- name: Skonfiguruj postgresql.conf, aby ustawić lokalizację danych
  ansible.builtin.lineinfile:
    path: /etc/postgresql/{{ postgresql_version }}/main/postgresql.conf
    regexp: '^data_directory'
    line: "data_directory = '/var/lib/postgresql'"
    owner: postgres
    group: postgres
    mode: '0644'
  become: true

# Sekcja: Uruchomienie i weryfikacja usługi PostgreSQL
- name: Restart PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
    enabled: true
  become: true
  tags: postgresql

- name: Sprawdź stan usługi PostgreSQL
  ansible.builtin.systemd:
    name: postgresql
    state: started
  register: postgresql_status

- name: Wyświetl stan usługi PostgreSQL
  ansible.builtin.debug:
    var: postgresql_status
