---
- name: Pobierz klucz PostgreSQL
  ansible.builtin.get_url:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    dest: /etc/apt/trusted.gpg.d/PostgreSQL.asc
    mode: '0644'
    force: false  # Unikaj ponownego pobierania klucza, jeśli już jest pobrany
  become: true
  when: not ansible_facts.packages['postgresql']

- name: Dodaj repozytorium PostgreSQL
  ansible.builtin.apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main"
    state: present
    update_cache: true
  become: true

- name: Instalacja pakietów PostgreSQL
  ansible.builtin.apt:
    name:
      - "postgresql-server-dev-{{ postgresql_version }}"
      - "postgresql-{{ postgresql_version }}-icu-ext"
      - "postgresql-contrib-{{ postgresql_version }}"
    state: present
    update_cache: true
  become: true
