---
- name: Pobierz klucz Nginx
  ansible.builtin.apt_key:
    url: "https://nginx.org/packages/mainline/ubuntu/dists/noble/Release.gpg"
    state: present

- name: Dodaj repozytorium Nginx
  ansible.builtin.apt_repository:
    repo: "deb http://nginx.org/packages/mainline/ubuntu {{ ansible_distribution_release }} nginx"
    state: present
    update_cache: true

- name: Instalacja pakietów nginx i certbota
  ansible.builtin.apt:
    name:
      - nginx
      - python3-certbot-nginx
    state: present
    update_cache: true

- name: Utworzenie katalogu dla Nginx
  ansible.builtin.file:
    path: "{{ nginx_web_dir }}"
    state: directory
    mode: "{{ nginx_mode_dir }}"
    owner: "{{ nginx_owner }}"
    group: "{{ nginx_group }}"

- name: Utworzenie katalogu letsencrypt
  ansible.builtin.file:
    path: "{{ letsencrypt_dir }}"
    state: directory
    mode: "{{ nginx_mode_dir }}"
    owner: root
    group: root

- name: Skopiowanie pliku konfiguracji SSL
  ansible.builtin.copy:
    src: options-ssl-nginx.conf
    dest: "{{ letsencrypt_dir }}/options-ssl-nginx.conf"
    mode: "{{ nginx_mode_file }}"
    owner: root
    group: root

- name: Usunięcie domyślnego pliku konfiguracyjnego Nginx
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Uruchomienie i włączenie usługi nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
