virtualmachines:
  hosts:
    vm01:
      #ansible_host: 192.168.1.189
      ansible_host: 192.168.0.209
    #server:
    #  ansible_host: ubuntu.etrust.pl
  vars:
    ansible_user: pawel
    ansible_become_password: C4llofduty87
    #ansible_user: root