---
- name: Configure Cron job for certbot
  ansible.builtin.cron:
    name: "certbot"
    job: "/usr/bin/certbot renew"
    user: "root"
    hour: "{{ 6 | random(seed=fqdn | string) }}"
    minute: "{{ 60 | random(seed=fqdn | string) }}"
    weekday: "{{ 6 | random(seed=fqdn | string) }}"

- name: Configure Cron job for Backup
  ansible.builtin.cron:
    name: "Backup"
    job: "/root/bin/cron.sh >/dev/null 2>&1"
    user: "root"
    minute: "05"
    hour: "1"

- name: Configure Cron job for apt-get update
  ansible.builtin.cron:
    name: "apt"
    job: "/usr/bin/apt-get update"
    user: "root"
    hour: "2"
    minute: "{{ 60 | random(seed=fqdn | string) }}"

- name: Configure Cron job for apt-get clean
  ansible.builtin.cron:
    name: "apt_clean"
    job: "/usr/bin/apt-get clean"
    user: "root"
    hour: "2"
    minute: "25"
    weekday: "1"
