---
- name: Pobierz klucz Zabbix
  ansible.builtin.get_url:
    url: http://repo.zabbix.com/zabbix-official-repo.key
    dest: /etc/apt/trusted.gpg.d/zabbix-archive-keyring.gpg

- name: Dodaj repozytorium Zabbix
  ansible.builtin.apt_repository:
    repo: "deb http://repo.zabbix.com/zabbix/6.4/ubuntu {{ ansible_distribution_release }} main"
    state: present
    update_cache: true

- name: Zainstaluj Zabbix Agent i zależności
  ansible.builtin.apt:
    name:
      - zabbix-agent
    state: present

- name: Nadaj uprawnienia dla /etc/zabbix/zabbix_agentd.conf
  ansible.builtin.file:
    path: /etc/zabbix/zabbix_agentd.conf
    owner: zabbix
    group: zabbix
    mode: '0644'

- name: Konfiguracja /etc/zabbix/zabbix_agentd.d
  ansible.builtin.file:
    path: /etc/zabbix/zabbix_agentd.d
    state: directory
    mode: '0640'
    owner: zabbix
    group: zabbix

- name: Konfiguracja /etc/zabbix/script
  ansible.builtin.file:
    path: /etc/zabbix/script
    state: directory
    mode: '0755'
    owner: zabbix
    group: zabbix

- name: Uruchom Zabbix Agent
  ansible.builtin.systemd:
    name: zabbix-agent
    state: started
    enabled: true
