---
- name: Aktualizacja pamięci podręcznej pakietów
  ansible.builtin.apt:
    update_cache: true

- name: Rozpakowanie Oracle Instant Client Basic 
  ansible.builtin.unarchive:
    src: "{{ oracle_basic_zip }}"
    dest: "{{ role_path }}/files"
    remote_src: false
  delegate_to: localhost

- name: Rozpakowanie Oracle Instant Client SDK
  ansible.builtin.unarchive:
    src: "{{ oracle_sdk_zip }}"
    dest: "{{ role_path }}/files"
    remote_src: false
  delegate_to: localhost

- name: Utworzenie katalogu
  ansible.builtin.file:
    path: "{{ oracle_dir }}"
    state: directory
    mode: '0755'

- name: Przeniesienie rozpakowanych plików Oracle Instant Client
  ansible.builtin.copy:
    src: "{{ role_path }}/files/instantclient_19_8"
    dest: "{{ oracle_client_dir }}"
    mode: '0755'
    owner: root
    group: root
  ignore_errors: true

- name: Utworzenie linków symbolicznych dla Oracle Instant Client
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: "{{ oracle_client_dir }}/instantclient_19_8/libclntsh.so.19.1", dest: "{{ oracle_client_dir }}/libclntsh.so" }
    - { src: "{{ oracle_client_dir }}/instantclient_19_8/libocci.so.19.1", dest: "{{ oracle_client_dir }}/libocci.so" }

- name: Dodanie ścieżki Oracle Instant Client do ld.so.conf.d
  copy:
    content: "/opt/oracle/instantclient_19_8\n"
    dest: /etc/ld.so.conf.d/oracle-instantclient.conf
    owner: root
    group: root
    mode: '0644'

- name: Konfiguracja /etc/ld.so.conf.d/oracle-instantclient.conf
  ansible.builtin.lineinfile:
    path: /etc/ld.so.conf.d/oracle-instantclient.conf
    line: "{{ oracle_client_dir }}"
    state: present
    create: true
    mode: '0644'
    owner: root
    group: root

- name: Reload dynamic linker configuration
  command: ldconfig
  become: true

- name: Instalacja pakietów wymaganych do kompilacji oci8
  ansible.builtin.apt:
    name:
      - php{{ php_version }}-dev
      - php-pear
      - build-essential
      - libaio-dev
      - systemtap-sdt-dev
      - php{{ php_version }}-xml
    state: present

- name: Sprawdzenie stanu biblioteki oci8
  ansible.builtin.shell: |
    set -o pipefail
    pecl list oci8
  ignore_errors: true
  register: oci8_status
  changed_when: false
  failed_when: false

- name: Pobranie i instalacja oci8
  ansible.builtin.shell: |
    /bin/bash -c 'set -o pipefail; echo "instantclient,/opt/oracle/instantclient_19_8" | pecl install oci8-{{ oci8_version }}'
  args:
    creates: /usr/lib/php/20200930/oci8.so
  environment:
    ORACLE_HOME: "/opt/oracle/instantclient_19_8"
    LD_LIBRARY_PATH: "/opt/oracle/instantclient_19_8"
  when: oci8_status.rc != 0 or "oci8" not in oci8_status.stdout

- name: Dodanie rozszerzenia oci8 do php.ini (FPM)
  ansible.builtin.lineinfile:
    path: "/etc/php/8.0/fpm/php.ini"
    line: "extension = oci8.so"
    state: present

- name: Dodanie rozszerzenia oci8 do php.ini (CLI)
  ansible.builtin.lineinfile:
    path: "/etc/php/8.0/cli/php.ini"
    line: "extension = oci8.so"
    state: present

- name: Restart php
  ansible.builtin.service:
    name: php8.0-fpm
    state: restarted
