---
- name: Dodaj repozytorium PHP
  apt_repository:
    repo: "deb http://ppa.launchpad.net/ondrej/php/ubuntu {{ ansible_distribution_release }} main"
    state: present
    update_cache: true

- name: Instalacja pakietów php
  apt:
    pkg:
    - php7.4-cgi
    - php7.4-fpm
    - php7.4-gd
    - php7.4-curl
    - php7.4-soap
    - php7.4-imagick
    - php7.4-xmlrpc
    - php7.4-sqlite3
    - php7.4-imap
    - php7.4-cli
    - php7.4-xml
    - php7.4-mbstring
    - php7.4-zip
    - php7.4-ldap
    - php7.4-intl
    - php7.4-bcmath
    state: present
