---
- name: Pobierz i dodaj klucz GPG dla BorgBackup
  ansible.builtin.apt_key:
    url: "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xe36ce452f7c2ae96fb1354901bcb19e03c2a1859"
    state: present

- name: Dodaj repozytorium BorgBackup
  ansible.builtin.apt_repository:
    repo: "deb http://ppa.launchpad.net/costamagnagianfranco/borgbackup/ubuntu {{ ansible_distribution_release }} main"
    state: present
    update_cache: true

- name: Instalacja najnowszej wersji pakietów
  ansible.builtin.package:
    name:
      - borgbackup2
      - nfs-common
      - certbot
    state: present
  when: "'borgbackup2' not in ansible_facts.packages"
