---
- name: Pobierz pakiet Zabbix Release
  ansible.builtin.get_url:
    url: "{{ zabbix_release_url }}"
    dest: "{{ zabbix_release_dest }}"
    mode: '0644'
    force: false

- name: Zainstaluj pakiet Zabbix Release
  ansible.builtin.command:
    cmd: "dpkg -i {{ zabbix_release_dest }}"
  changed_when: false

- name: Zaktualizuj cache APT
  ansible.builtin.apt:
    update_cache: true

- name: Zainstaluj Zabbix Agent i zależności
  ansible.builtin.apt:
    name:
      - zabbix-agent
      - zabbix-sender
    state: present

- name: Skonfiguruj plik zabbix_agentd.conf
  ansible.builtin.template:
    src: templates/zabbix_agentd.conf.j2
    dest: "{{ zabbix_agent_conf }}"
    mode: '0644'
    owner: 'root'
    group: 'root'
  notify: Restart Zabbix Agent

- name: Skonfiguruj katalog zabbix_agentd.d
  ansible.builtin.copy:
    src: files/zabbix_agentd.d/
    dest: "{{ zabbix_agentd_dir }}"
    owner: 'zabbix'
    group: 'zabbix'
    mode: '0640'
    force: true
  notify: Restart Zabbix Agent

- name: Skonfiguruj katalog script
  ansible.builtin.copy:
    src: files/script/
    dest: "{{ zabbix_script_dir }}"
    owner: 'zabbix'
    group: 'zabbix'
    mode: '0755'
    force: true
  notify: Restart Zabbix Agent

- name: Skonfiguruj katalog zabbix_agentd.conf.d
  ansible.builtin.file:
    path: "{{ zabbix_agentd_conf_d }}"
    state: directory
    owner: 'zabbix'
    group: 'zabbix'
    mode: '0640'
  notify: Restart Zabbix Agent

  handlers:
    - name: Restart Zabbix Agent
      ansible.builtin.service:
        name: zabbix-agent
        state: restarted
        enabled: true
