---
- name: Pobierz pakiet Zabbix Release
  ansible.builtin.get_url:
    url: "{{ zabbix_release_url }}"
    dest: "{{ zabbix_release_dest }}"
    mode: '0644'
    force: false

- name: Zainstaluj pakiet Zabbix Release
  ansible.builtin.command:
    cmd: "dpkg -i {{ zabbix_release_dest }}"
  changed_when: false

- name: Zaktualizuj cache APT
  ansible.builtin.apt:
    update_cache: true

- name: Zainstaluj Zabbix Agent i zależności
  ansible.builtin.apt:
    name: zabbix-agent
    state: present

- name: Nadaj uprawnienia dla zabbix_agentd.conf
  ansible.builtin.file:
    path: "{{ zabbix_agent_conf }}"
    owner: zabbix
    group: zabbix
    mode: '0644'
  become: true

- name: Konfiguracja zabbix_agentd.d
  ansible.builtin.file:
    path: "{{ zabbix_agentd_dir }}"
    state: directory
    mode: '0750'
    owner: zabbix
    group: zabbix
  become: true

- name: Konfiguracja zabbix script
  ansible.builtin.file:
    path: "{{ zabbix_script_dir }}"
    state: directory
    mode: '0755'
    owner: zabbix
    group: zabbix
  become: true

- name: Uruchom i włącz Zabbix Agent
  ansible.builtin.systemd:
    name: zabbix-agent
    state: started
    enabled: true
