---
# Sekcja: Pobieranie i instalacja Zabbix Release
- name: Pobierz pakiet Zabbix Release
  ansible.builtin.get_url:
    url: "{{ zabbix_release_url }}"
    dest: "{{ zabbix_release_dest }}"
    mode: '0644'
    force: false

- name: Zainstaluj pakiet Zabbix Release
  ansible.builtin.command:
    cmd: "dpkg -i {{ zabbix_release_dest }}"
  changed_when: false

- name: Zaktualizuj cache APT
  ansible.builtin.apt:
    update_cache: true

# Sekcja: Instalacja Zabbix Agent i zależności
- name: Zainstaluj Zabbix Agent i zależności
  ansible.builtin.apt:
    name:
      - zabbix-agent
      - zabbix-sender
    state: present

# Sekcja: Konfiguracja pliku zabbix_agentd.conf
- name: Skonfiguruj zabbix_agentd.conf
  ansible.builtin.copy:
    content: |
      # Zabbix Agent configuration file
      Server=127.0.0.1
      Hostname=Zabbix server
      Include={{ zabbix_agentd_dir }}/*.conf
    dest: "{{ zabbix_agent_conf }}"
    owner: zabbix
    group: zabbix
    mode: '0644'
  become: true

# Sekcja: Konfiguracja zabbix_agentd.d
- name: Konfiguracja zabbix_agentd.d
  ansible.builtin.file:
    path: "{{ zabbix_agentd_dir }}"
    state: directory
    mode: '0750'
    owner: zabbix
    group: zabbix
  become: true

# Sekcja: Konfiguracja zabbix script
- name: Konfiguracja zabbix script
  ansible.builtin.file:
    path: "{{ zabbix_script_dir }}"
    state: directory
    mode: '0755'
    owner: zabbix
    group: zabbix
  become: true

# Sekcja: Uruchomienie i weryfikacja usługi Zabbix Agent
- name: Uruchom i włącz Zabbix Agent
  ansible.builtin.systemd:
    name: zabbix-agent
    state: started
    enabled: true
  become: true

- name: Sprawdź stan usługi Zabbix Agent
  ansible.builtin.systemd:
    name: zabbix-agent
    state: started
  register: zabbix_agent_status

- name: Wyświetl stan usługi Zabbix Agent
  ansible.builtin.debug:
    var: zabbix_agent_status
