---
- name: Pobierz klucz Nginx
  get_url:
    url: "https://cs.nginx.com/static/keys/nginx_signing.key"
    dest: /etc/apt/trusted.gpg.d/nginx.asc
    mode: '0644'
    force: true

- name: Dodaj repozytorium Nginx
  apt_repository:
    repo: "deb http://nginx.org/packages/mainline/ubuntu {{ ansible_distribution_release }} nginx"
    state: present
    update_cache: true

- name: Instalacja pakietów nginx
  apt:
    pkg:
      - nginx
      - python3-certbot-nginx
    state: present
